### ISSUE TITLE
Tool References

### ISSUE THREAD

**Issue by vwichmann** [openwebcc/sagadoc#1]
Hi Klaus,

since some time there is a new tool description function in SAGA for references: Get_References()

The attached patch implements that in sagadoc, please review.

Not all tools use this function already, so there are still a lot of tools that simply have the references listed in the description. I've just uploaded the tool reference for SAGA 4.0.1 with the patch applied. A tool that already uses the Get_References() function is [Slope, Aspect, Curvature](http://www.saga-gis.org/saga_tool_doc/4.0.1/ta_morphometry_0.html).

Cheers,
Volker

[sagadoc_references.patch.zip](https://github.com/openwebcc/sagadoc/files/888379/sagadoc_references.patch.zip)

**Comment by openwebcc** [comment]
Hi Volker,

I've committed your (slightly altered) patch. I've removed the if-clause while setting the template term as toolreferences_2_str returns an empty string if no references are found already. The second minor change is replacing the i-tag with an em-tag to emphasis the heading "References".

Please fell free to test this version and apply it to the next SAGA release.

Thanks for your contribution Volker,
Klaus
